apiVersion: apps/v1
kind: Deployment
metadata:
  name: skil-web-server
  namespace: skil
  labels:
    app: apache
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apache
  template:
    metadata:
      labels:
        app: apache
    spec:
      containers:
      - name: php-apache
        image: gcr.io/yescloud/galaxyback
        ports:
        - containerPort: 80
        volumeMounts:
        - name: skil-pvc-sym-m
          mountPath: /var/www/upload/image
      volumes:
      - name: skil-pvc-sym-m
        persistentVolumeClaim:
          claimName: skil-pvc-sym-uploud
---
apiVersion: v1
kind: Service
metadata:
  name: skil-web-service
  namespace: skil
  labels:
    run: skil-web-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
    protocol: TCP
  selector:
    app: apache
---
apiVersion: v1                  
kind: PersistentVolumeClaim     
metadata:                       
   name: skil-pvc-sym-uploud
   namespace: skil
spec:                           
   accessModes:                  
   - ReadWriteOnce              
   resources:                   
      requests:                 
         storage: 1Gi   
