name: Deploy to cloud
on:
  push:
    branches: [ d-cloud ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy backend app
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{secrets.SSH_HOST}} # IP address of the server you wish to ssh into
          key: ${{secrets.SSH_KEY}} # Private or public key of the server
          username: ${{ secrets.SSH_USERNAME }} # User of the server you want to ssh into
     
          script: |
            cd ..
            cd ..
            cd var/www/backend-skeleton 
            git pull https://github.com/yes-soft-de/symfony-app-skeleton d-cloud
      container:
        image: backend-skeleton_php74-service
      steps:
        - uses: actions/checkout@v2
        - run: |
            echo I am insaid php container
            echo It runs in the container instead of the VM.
            php bin/console make:migration
            php bin/console doctrine:migrations:migrate
          name: Run in container
